### ISSUE TITLE
测试数据无法下载

### ISSUE THREAD

**Issue by wondering516** [GenghisYoung233/Gaofen-Batch#1]
**请求下载测试数据，目前无操作权限**

**Comment by GenghisYoung233** [comment]
抱歉，谷歌网盘账号失联了，Worker也被墙了。找了个r2网盘，不知道能坚持多久。
[GF1B-PMS](https://pub-21215d6624134fd2a1ddc0068cc58728.r2.dev/GF1B_PMS_E113.6_N30.2_20200804_L1A1227847119.tar.gz)
[GF1C-PMS](https://pub-21215d6624134fd2a1ddc0068cc58728.r2.dev/GF1C_PMS_E114.6_N38.0_20200903_L1A1021638673.tar.gz)
[GF1D-PMS](https://pub-21215d6624134fd2a1ddc0068cc58728.r2.dev/GF1D_PMS_E118.9_N25.2_20200618_L1A1256758761.tar.gz)
[GF1-PMS](https://pub-21215d6624134fd2a1ddc0068cc58728.r2.dev/GF1_PMS1_E116.4_N35.3_20201111_L1A0005183179.tar.gz)
[GF1-WFV](https://pub-21215d6624134fd2a1ddc0068cc58728.r2.dev/GF1_WFV2_E115.2_N44.3_20200621_L1A0004883904.tar.gz)
[GF2-PMS](https://pub-21215d6624134fd2a1ddc0068cc58728.r2.dev/GF2_PMS1_E110.0_N24.4_20180206_L1A0002986008.tar.gz)
[GF2-PMS](https://pub-21215d6624134fd2a1ddc0068cc58728.r2.dev/GF2_PMS2_E110.2_N24.0_20180206_L1A0002987285.tar.gz)
[GF5B_AHSI](https://pub-21215d6624134fd2a1ddc0068cc58728.r2.dev/GF5B_AHSI_E114.3_N34.8_20211125_001151_L10000029423.tar.xz)
[GF5B_VIMI](https://pub-21215d6624134fd2a1ddc0068cc58728.r2.dev/GF5B_VIMI_N47.1_E131.4_20211020_000626_L10000014371.tar.xz)
[GF6_PMS](https://pub-21215d6624134fd2a1ddc0068cc58728.r2.dev/GF6_PMS_E120.6_N31.3_20200524_L1A1120000424.tar.gz)
[GF6_WFV](https://pub-21215d6624134fd2a1ddc0068cc58728.r2.dev/GF6_WFV_E119.9_N35.8_20190909_L1A1119923795.tar.gz)
[GF7_DLC](https://pub-21215d6624134fd2a1ddc0068cc58728.r2.dev/GF7_DLC_E80.6_N44.1_20210819_L1A0000535233.tar.gz)

**Comment by DoomfistOnly** [comment]
抱歉，谷歌网盘账号失联了，Worker也被墙了。浅嫖了一个Cloudflare R2网盘，不知道能坚持多久。
[GF1B-PMS](https://pub-21215d6624134fd2a1ddc0068cc58728.r2.dev/GF1B_PMS_E113.6_N30.2_20200804_L1A1227847119.tar.gz)
[GF1C-PMS](https://pub-21215d6624134fd2a1ddc0068cc58728.r2.dev/GF1C_PMS_E114.6_N38.0_20200903_L1A1021638673.tar.gz)
[GF1D-PMS](https://pub-21215d6624134fd2a1ddc0068cc58728.r2.dev/GF1D_PMS_E118.9_N25.2_20200618_L1A1256758761.tar.gz)
[GF1-PMS](https://pub-21215d6624134fd2a1ddc0068cc58728.r2.dev/GF1_PMS1_E116.4_N35.3_20201111_L1A0005183179.tar.gz)
[GF1-WFV](https://pub-21215d6624134fd2a1ddc0068cc58728.r2.dev/GF1_WFV2_E115.2_N44.3_20200621_L1A0004883904.tar.gz)
[GF2-PMS](https://pub-21215d6624134fd2a1ddc0068cc58728.r2.dev/GF2_PMS1_E110.0_N24.4_20180206_L1A0002986008.tar.gz)
[GF2-PMS](https://pub-21215d6624134fd2a1ddc0068cc58728.r2.dev/GF2_PMS2_E110.2_N24.0_20180206_L1A0002987285.tar.gz)
[GF5B_AHSI](https://pub-21215d6624134fd2a1ddc0068cc58728.r2.dev/GF5B_AHSI_E114.3_N34.8_20211125_001151_L10000029423.tar.xz)
[GF5B_VIMI](https://pub-21215d6624134fd2a1ddc0068cc58728.r2.dev/GF5B_VIMI_N47.1_E131.4_20211020_000626_L10000014371.tar.xz)
[GF6_PMS](https://pub-21215d6624134fd2a1ddc0068cc58728.r2.dev/GF6_PMS_E120.6_N31.3_20200524_L1A1120000424.tar.gz)
[GF6_WFV](https://pub-21215d6624134fd2a1ddc0068cc58728.r2.dev/GF6_WFV_E119.9_N35.8_20190909_L1A1119923795.tar.gz)
[GF7_DLC](https://pub-21215d6624134fd2a1ddc0068cc58728.r2.dev/GF7_DLC_E80.6_N44.1_20210819_L1A0000535233.tar.gz)

**Comment by NtskwK** [comment]
新的下载链接貌似也失效了
